---
- set_fact:
    beta_or_ga: beta-confluent
  when: package == "beta-confluent-kafka-zookeeper" or package == "beta-confluent-kafka"

- set_fact:
    beta_or_ga: confluent
  when: package == "confluent-kafka-zookeeper" or package == "confluent-kafka-zookeeper"

- name: Build the create_keytabs batch script in the output directory
  template: src=templates/create_keytabs.bat.j2 dest=roles/setup/tasks/output/create-keytabs.bat

- name: Build the client-jaas.conf in the output directory
  template: src=templates/client-jaas.conf.j2 dest=roles/setup/tasks/output/client-jaas.conf

- name: Build the client.properties in the output directory
  template: src=templates/client.properties.j2 dest=roles/setup/tasks/output/client.properties

- name: Build the krb5.conf in the output directory
  template: src=templates/krb5.conf.j2 dest=roles/setup/tasks/output/krb5.conf